name: generate animation

on:
  schedule:
    - cron: "0 */24 * * *" # Every 24 hours
  workflow_dispatch: # Manual trigger
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 5

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=white&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      - name: Upload snake files
        uses: actions/upload-artifact@v4
        with:
          name: snake-artifacts
          path: dist/

      - name: Download snake artifacts
        uses: actions/download-artifact@v4
        with:
          name: snake-artifacts
          path: snake-commit-contribution

      - name: Show contents
        run: ls -la snake-commit-contribution

      - name: Commit and push to main
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add snake-commit-contribution/*
          git commit -m "chore: update contribution snake assets in snake-commit-contribution" || echo "No changes to commit"
          git push origin main
