name: generate animation

on:
  schedule:
    - cron: "0 */24 * * *"  # Every 24 hours
  workflow_dispatch:        # Manual trigger
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 5

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg?palette=#ffffffcc,#ffffff99,#ffffff66,#ffffff33
            dist/github-contribution-grid-snake-dark.svg?palette=#ffffffcc,#ffffff99,#ffffff66,#ffffff33

      - name: Create snake-commit-contribution folder if not exists and move files
        run: |
          mkdir -p snake-commit-contribution
          mv dist/*.svg snake-commit-contribution/

      - name: Commit and push to main
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add snake-commit-contribution/*.svg
          git commit -m "chore: update contribution snake SVGs in snake-commit-contribution" || echo "No changes to commit"
          git push origin main
